### ISSUE TITLE
XML dump

### ISSUE THREAD

**Issue by fpbarthel** [chrisamiller/igvScreenshot#1]
Hi!

Do you know if there is a script around that creates the IGV XML file? The one you are referencing (https://github.com/genome/genome/blob/master/lib/perl/Genome/Model/Tools/Analysis/DumpIgvXmlMulti.pm) is a module for a suite of applications and does not work standalone. As I'm not familiar with perl it won't be easy for me to make it working. Any pointers?

Thanks!
Floris

**Comment by chrisamiller** [comment]
The easiest way to generate one is to load up a session, then take your existing XML file and replace the relevant portions with the correct version of your bams.  It'd also be pretty straightforward to extract the guts of that script from the GMS wrapping.  Best of luck
